### PR TITLE
Gemified

### PR DESCRIPTION
**Pull request by sethherr**
Make this something that is useable as a gem, so it can more easily be included in the Fusion project.

I need help with this: it's almost there, but the c is failing to compile. It spits out error messages, and as someone who doesn't deal with c, it's confusing and I don't know what to do.

Error message gist: https://gist.github.com/sethherr/74a4d7b73747fea84ab1

Once this successfully compiles, I'll be able to add this to fusion and deploy it, so if someone helps it would be awesome...

### CODE REVIEW

**Comment by sethherr** [comment]
It appears that this is an issue with the JSON file that is provided? Or perhaps the template. I can get it to compile non-liquid c files.

**Comment by ezuk** [comment]
@tdegrunt - do you think it might be the Liquid escaping too much stuff?

**Comment by sethherr** [comment]
Two notes about the changes on this:
- I changed the name to keyboard_reactor because there is already a [gem named reactor](https://rubygems.org/gems/reactor)
- I added `.ruby-version` and `.ruby-gemset` to the .gitignore. I still have those files (and I understand if your editor requires them, just add them back in after switching to this repository)

**Comment by tdegrunt** [comment]
TO(1) should probably be TG(1), it was changed at the time when I wrote the example JSON and the keymaps:
https://github.com/jackhumbert/qmk_firmware/blob/master/quantum/keymap_common.h#L184

**Comment by sethherr** [comment]
@tdegrunt I updated the JSON with TG(1), now I'm getting a different error:

```
./ergodox_ez.h:111:25: error: expected expression before ',' token
     { k08, k18, k28, k38,KC_NO, k58 },   \
                         ^
keymaps/keymap_145149885321reactor.c:13:7: note: in expansion of macro 'KEYMAP'
 [1] = KEYMAP(KC_TRANSPARENT,KC_F1,KC_F2,KC_F3,KC_F4,KC_F5,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_F6,KC_F7,KC_F8,KC_F9,KC_F10,KC_F11,KC_TRANSPARENT,KC_UP,KC_KP_7,KC_KP_8,KC_KP_9,KC_KP_ASTERISK,KC_F12,KC_DOWN,KC_KP_4,KC_KP_5,KC_KP_6,KC_KP_PLUS,KC_TRANSPARENT,KC_TRANSPARENT,,KC_KP_1,KC_KP_2,KC_KP_3,KC_KP_SLASH,KC_TRANSPARENT,KC_TRANSPARENT,KC_KP_DOT,KC_KP_0,KC_KP_EQUAL,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT),
       ^
keymaps/keymap_145149885321reactor.c: In function 'matrix_init_user':
keymaps/keymap_145149885321reactor.c:41:1: warning: control reaches end of non-void function [-Wreturn-type]
 };
 ^
keymaps/keymap_145149885321reactor.c: In function 'matrix_scan_user':
keymaps/keymap_145149885321reactor.c:65:1: warning: control reaches end of non-void function [-Wreturn-type]
 };
 ^
make: *** [obj_145149885321reactor/keymaps/keymap_145149885321reactor.o] Error 1
```

**Comment by tdegrunt** [comment]
Are there 72 items in the array?

**Comment by sethherr** [comment]
There are 84 items in the first layer `keymap` array.

**Pull request merged**
